---

- name: Provision Vagrant VM
  hosts: all
  become: True
  gather_facts: False

  tasks:
      - name: Create dir for storing apt cache in /vagrant
        file: state=directory path=/vagrant/apt/cache/partial

      - name: Set apt cache location
        copy: content='dir::cache::archives "/vagrant/apt/cache";' dest=/etc/apt/apt.conf.d/cache

      - debug: msg="Running 'apt dist-upgrade', this may take a while..."

      # May take a while...
      - name: Apt dist-upgrade
        apt: update_cache=yes upgrade=dist cache_valid_time=3600


      - name: Install vim, git, ansible, python-keyczar, expect
        apt:
          name:
          - vim
          - git
          - ansible
          - python-keyczar
          - expect