# Vagrant configuration file for a development VM
# Works with vmware fusion and virtual box providers

Vagrant.configure("2") do |config|

    # The VM Image to use. Find others at: http://vagrantcloud.com
    # The puppetlabs/ubuntu-16.04-64-nocm box supports both a VMware and a virtual box
    # Note: The "nocm" version of this box does not have any puppet software installed
    config.vm.box = "puppetlabs/ubuntu-16.04-64-nocm"

    # VM: "dev-vm"
    config.vm.define "dev-vm" do |conf|
        # Workaround for "port 2222 in use error" with "vagrant up". Vagrant cannot fix this automatically
        # Instead of the default 2222, use a randomly selected port from the range 1000-5000.
        r = Random.new
        ssh_port = r.rand(1000...5000)
        config.vm.network "forwarded_port", guest: 22, host: "#{ssh_port}", id: 'ssh', auto_correct: true
        conf.vm.hostname = "dev-vm"
        # Give the VM a fixed IP. This allows using /etc/hosts and makes setting up host base network with
        # multiple VMs that can reach each other much simpler
        conf.vm.network "private_network", ip: "192.168.66.66", :netmask => "255.255.255.0"
        conf.vm.provider "vmware_fusion" do |v|
            v.vmx["memsize"] = "1024"
        end
        conf.vm.provider "virtualbox" do |v|
            v.memory = 1024
        end
    end

#    # VM: "dev-vm2"
#    config.vm.define "dev-vm2" do |conf|
#        r = Random.new
#        ssh_port = r.rand(1000...5000)
#        config.vm.network "forwarded_port", guest: 22, host: "#{ssh_port}", id: 'ssh', auto_correct: true
#        conf.vm.hostname = "dev-vm2"
#        # Give it a fixed IP
#        conf.vm.network "private_network", ip: "192.168.66.67", :netmask => "255.255.255.0"
#        conf.vm.provider "vmware_fusion" do |v|
#            v.vmx["memsize"] = "1024"
#        end
#        conf.vm.provider "virtualbox" do |v|
#            v.memory = 1024
#        end
#    end

    config.vm.provision "ansible" do |ansible|
        # Groups to add to the Ansible inventory file generated by Vagrant
        # For use by ansible-playbook later.
        # These are not used by provision.yml

        ansible.compatibility_mode = "2.0"
        ansible.groups = {
          "example" => ["dev-vm"],
        }
        ansible.playbook = "provision-vagrant-vm.yml"
        #ansible.verbose = "vvvv" # For troubleshooting ansible connection problems
    end

end
