---

- name: restart netfilter-persistent
  service: name=netfilter-persistent state=restarted

- name: restart ntpd
  service: name=ntpd state=restarted

# Include handlers for environment specific tasks
#- include_tasks: "{{ inventory_dir }}/handlers/common.yml"