---

- name: restart iptables-persistent
  service: name=iptables-persistent state=reloaded

- name: restart ntpd
  service: name=ntpd state=restarted

# Include handlers for environment specific tasks
#- include_tasks: "{{ inventory_dir }}/handlers/common.yml"