---

- name: Plain include
  import_tasks: example_include.yml

- name: Include with var=value syntax
  import_tasks: example_include.yml variable1=First variable2=Second

- name: Include with var map syntax
  import_tasks: example_include.yml
  vars:
    variable1: First
    variable2: Second

- name: Include, set vars from other vars
  import_tasks: example_include.yml
  vars:
    variable1: "{{ example_string1 }}"
    variable2: "{{ example_dictionary1 }}"

- name: Include, set vars direct
  import_tasks: example_include.yml
  vars:
    variable2: { a: 1, b: 2, c: 3 }