---

- name: Examples -- task syntax
  import_tasks: task_syntax.yml

- name: Example -- with_items
  import_tasks: with_items_syntax.yml

- name: Example -- include syntax
  import_tasks: include_syntax.yml

- name: Example -- task options
  import_tasks: task_options.yml