---

- name: with_items with an in place list
  debug: msg="{{ item }}"
  with_items:
  - 1
  - 2
  - 3

# Same as above
- name: with_items with an in place list
  debug: msg="{{ item }}"
  with_items: [ 1, 2, 3 ]

- name: Print each item in example_list1
  debug: msg="{{ item }}"
  with_items: "{{ example_list1 }}"

- name: Print each item in example_list_of_dict1
  debug: msg="{{ item.item1 }}; {{ item['item2'] }}"
  with_items: "{{ example_list_of_dict1 }}"

- name: with_items with an in place list of dict (1)
  debug: msg="{{ item.a }}={{ item.b }}"
  with_items: [ { a: 1, b: one }, { a: 2, b: two }, { a: 3, b: three } ]

- name: with_items with an in place list of dict (2)
  debug: msg="{{ item.a }}={{ item.b }}"
  with_items:
  - a: 1
    b: one
  - a: 2
    b: two
  - a: 3
    b: three
